### ISSUE TITLE
Game freezes after Choose Hero button click when multiplayer is on.

### ISSUE THREAD

**Issue by LingASDJ** [Nikita22007/pixel-dungeon-multiplayer#6]
[Download Question Video](https://media.discordapp.net/attachments/884481743967617044/1009848251631030393/Question.mp4)

**Comment by LingASDJ** [comment]
Androd10,Redmi9

**Comment by Nikita22007** [comment]
fixed at commit f0b3137d6966e2f84df1d8c1ed4f3df184033a12
